spring:
  application:
    name: orden-trabajo-microservice
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/orden_trabajo_microservice}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://desa-sso-etimet.taurus-ts.com/realms/Etimet}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:https://desa-sso-etimet.taurus-ts.com/realms/Etimet/protocol/openid-connect/certs}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}
    virtual-host: ${RABBIT_VHOST:/}
    ssl:
      enabled: ${RABBIT_SSL_ENABLED:false}
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        default-requeue-rejected: false
server:
  port: 8080

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%-5level) %clr(%logger{10}){cyan} - %msg%n"
